### PR TITLE
fix: fixes method look-up on interfaces

### PR DESCRIPTION
**Pull request by jacaetevha**
`getDeclaredMethod` doesn't work when the given class is an interface.

### CODE REVIEW

**Comment by astonbitecode** [comment]
Hi, thanks for contributing.

Can you please tell me what you are trying to achieve? 

From what I understand, what you are trying to do is instance creation and casting in one step.

However, the constructor `public JsonInvocationImpl(T instance, Class<T> clazz)` is invoked by the "Java world" only and should not be used for casting a created instance to some superclass or interface.

The way that this should be done, should be first to create the instance that you want and then cast it to the class that you need.
Of course, you can use the [chaining operations](https://github.com/astonbitecode/j4rs#java-instances-chaining) to avoid some boilerplate.

Regarding the feature proposal for the logging, the arguments were explicitly left out, in order not to expose sensitive information.

**Comment by jacaetevha** [comment]
There are two problems that this PR addresses.

1. using `getDeclaredMethod` doesn't work if the instance coming in is an interface and the interface inherits the method declaration from a super-interface:
```java
jshell> java.util.List.class.getDeclaredMethod("add")
|  java.lang.NoSuchMethodException thrown: java.util.List.add()
|        at Class.getDeclaredMethod (Class.java:2432)
|        at (#3:1)
```

2. `getMethod` and `getDeclaredMethod` for genericized classes/interfaces doesn't find the method when you're passing in the actual classes of the arguments instead of `java.lang.Object.class` since the compiler removes the generic information:

```
jshell> List<String> list = new ArrayList<>();
list ==> []

jshell> list.getClass().getMethod("add", new Class[]{String.class})
|  java.lang.NoSuchMethodException thrown: java.util.ArrayList.add(java.lang.String)
|        at Class.getMethod (Class.java:2065)
|        at (#6:1)

jshell> list.getClass().getDeclaredMethod("add", new Class[]{String.class})
|  java.lang.NoSuchMethodException thrown: java.util.ArrayList.add(java.lang.String)
|        at Class.getDeclaredMethod (Class.java:2432)
|        at (#7:1)

jshell> list.getClass().getMethod("add", new Class[]{Object.class})
$8 ==> public boolean java.util.ArrayList.add(java.lang.Object)

jshell> list.getClass().getDeclaredMethod("add", new Class[]{Object.class})
$9 ==> public boolean java.util.ArrayList.add(java.lang.Object)
```

RE: the extra logging, that's been removed. I didn't actually mean to commit that. I was using it to help debug the issue.

**Comment by astonbitecode** [comment]
You are right about the differences between `getDeclaredMethod` and `getMethod`, I understand both of the points you are trying to address. However, all these are regarding the Java lang side.

I am asking what you are trying to achieve, because what you are doing in the unit test you have added can be achieved with j4rs from the rust side with a simple cast. 

I have added a [unit test](https://github.com/astonbitecode/j4rs/blob/9ee84a06521168be8a876a87441e8a6216c7528a/rust/src/lib.rs#L553) in the Rust side to make my point clear. If you comment-out the cast to `java.util.Map` in line 561 you get the method not found exception. With the cast though, the test case works.

**Comment by astonbitecode** [comment]
Nevertheless, we can add the impl of using getMethod in case of interfaces to avoid the need for casting.

**Comment by jacaetevha** [comment]
Sorry. I see what you're saying now. However, I think it's really unnecessary to have to do the cast in the Rust side, when Java can simply get it for you via the correct method call. That only addresses the 1st problem 1.

Can the 2nd problem be addressed on the Rust side as well by casting the `Instance` we get back to a `java.lang.Object`? If so, that's a lot more verbose than just allowing for the alternative `from` implementation.

(For what it's worth, the application I'm working on is an interop from Rust to Java for a Hazelcast-backed service, where the objects we get back from the Java side are proxy implementations to remote distributed objects. E.g. the `com.hazelcast.core.IMap` interface which gives back one of a few implementations based on the nature of the `IMap`).

**Comment by astonbitecode** [comment]
I merged your first commit, but then, in the need to address the second point, I changed the implementation of `JsonInvocationImpl.findMethodInHierarchy`.

I have pushed a first approach in the master, which seems to work. You may see the added tests in both Java and Rust side.

However, exactly because of the types erasure, there is no type safety and this may lead to weird situations.

[Here](https://github.com/astonbitecode/j4rs/blob/e55789d6441c4909430cc99d2c4a1ac034e70ae8/rust/src/lib.rs#L569) is a test in the Rust side for reference.

Anyhow, if you face problems with the impl in the master please let me know. In the meantime I will be investigating if there is a better approach.

Maybe it would be better if the caller (Rust side) controlled when an InvocationArgument should be used as a generic one instead of letting the reflection to potentially mess up, but then, 
things could be more verbose and uncomfort.

**Comment by jacaetevha** [comment]
OK. I'll give this a try tomorrow. Thanks for the expansion.

**Pull request closed without merging**
