### PR TITLE
Collect all Java dependencies in one JAR file

### PR DESCRIPTION
**Pull request by stefano-pogliani**
Hello,

I've just stared using `j4rs` for a new project and initialising a JVM instance results in the error below:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
        at org.astonbitecode.j4rs.api.dtos.InvocationArgGenerator.lambda$generateArgObjects$0(InvocationArgGenerator.java:33)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
        at org.astonbitecode.j4rs.api.dtos.InvocationArgGenerator.generateArgObjects(InvocationArgGenerator.java:39)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:63)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 10 more
```

I've tried to set the classpath attribute but it seems the only option that worked was to manually add every jar file in `lib/` to the classpath `Vec` passed as the first argument of `new_jvm`.

It seems that packaging all the dependencies into one and pointing to it as the default library solves the problem and is much nicer user experience.
Is there any interest in an all-in-one dependencies JAR?

### CODE REVIEW

**Comment by astonbitecode** [comment]
Hi, thank you for the suggestion. 
You actually found a bug that existed in the pom. 

The MANIFEST of the j4rs jar file should contain a classpath entry like the following:
`Class-Path: lib/logback-classic-1.2.2.jar lib/logback-core-1.2.2.jar lib/slf4j-api-1.7.25.jar lib/jackson-core-2.9.0.pr3.jar lib/jackson-databind-2.9.0.pr3.jar lib/jackson-annotations-2.9.0.pr3.jar`

The maven-jar-plugin should build the classpath as above. However, the problem was that the maven-jar-plugin was re-declared under the __release__ profile and this declaration did not contain the classpath configuration...
Anyway, I agree with your suggestion. It is cleaner and simpler this way (even though not so maven-correct), so, let's be pragmatic and merge this to the master.

I will just clean up the pom first... Of course, it seems that I should yank the 0.1.4 release in the crates.io and publish a new one containing your changes...

**Comment by astonbitecode** [comment]
Hi, thank you for the suggestion. 
You actually found a bug that existed in the pom. 

The MANIFEST of the j4rs jar file should contain a classpath entry like the following:
`Class-Path: lib/logback-classic-1.2.2.jar lib/logback-core-1.2.2.jar lib/slf4j-api-1.7.25.jar lib/jackson-core-2.9.0.pr3.jar lib/jackson-databind-2.9.0.pr3.jar lib/jackson-annotations-2.9.0.pr3.jar`

The maven-jar-plugin should build the classpath as above. However, the problem was that the maven-jar-plugin was re-declared under the __release__ profile and this declaration did not contain the classpath configuration...
Anyway, I agree with your suggestion. It is cleaner and simpler this way (even though not so maven-correct), so, let's be pragmatic and merge this to the master.

I will just clean up the pom first... Of course, it seems that I should yank the 0.1.4 release in the crates.io and publish a new one containing your changes...

**Comment by astonbitecode** [comment]
Published this in [crates.io](https://crates.io/crates/j4rs/0.1.5) and [yanked the 0.1.4](https://crates.io/crates/j4rs/0.1.4). 

@stefano-pogliani thanks for your contribution!

**Comment by stefano-pogliani** [comment]
Thank you!

For this as well as for `j4rs` itself :smile:

**Pull request merged**
